---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 4440, host: 4440}]

provisioner:
  name: chef_solo
  attributes:
    rundeck:
      admin_password: admin # Useful for manual checking sometimes

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: centos-6.5

suites:
- name: default
  run_list:
  - recipe[rundeck]
- name: simple
  run_list:
  - recipe[rundeck]
  - recipe[rundeck_test::simple]
- name: jar
  run_list:
  - recipe[rundeck_test::jar]
  - recipe[rundeck_test::simple]
- name: delete_job
  run_list:
  - recipe[rundeck]
  - recipe[rundeck_test::delete_job]
