---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
  - ["forwarded_port", {guest: 4440, host: 4441}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[rundeck]
- name: simple
  run_list:
  - recipe[rundeck]
  - recipe[rundeck_test::simple]
